# -*- coding: utf-8 -*-
"""analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1krb0j0qFQUduK3i1nNunSZelbVWJuz9q

# New section
"""

import pandas as pd
import matplotlib.pyplot as plt

dataframe = pd.read_csv('nypd.csv')
# read top 10 rows
dataframe.head(10)

"""**Check null values in the dataframe columns**"""

dataframe.isnull().sum()

"""**check the shape and size  of dataframe**"""

print(f'the number of rows : {dataframe.shape[0]}')
print(f'the number of columns :{dataframe.shape[1]}')

percentageOfNull = dataframe.isnull().sum()/len(dataframe) * 100

percentageOfNull

dataframe.columns

"""**Remove null values columns with null value percentage more than 50%**"""

dataframe = dataframe.drop(labels=['Arrest Id','Arrest Date'], axis=1)
dataframe.isnull().sum()

"""**Categorical columns and numerical columns**"""

df = dataframe
df.columns

cols = df.columns

numerical_Col = df._get_numeric_data().columns
print(numerical_Col)

categorical_Col = list(set(cols) - set(numerical_Col))
categorical_Col

"""**Show top offensive category**"""

offensive_cat = df['Offense Category'].value_counts()
offensive_cat

import seaborn as sns

sns.countplot(x='Offense Category', data=df);
plt.xticks(rotation=65, horizontalalignment='right');

"""**Which county has more crime**"""

df['County'].value_counts()

sns.countplot(x='County', data=df);
plt.xticks(rotation=65, horizontalalignment='right');

gkk = df.groupby(['Month Number'])['Offense Category'].count()
gkk

gkk.plot();

df[['Offense Category']].apply(pd.Series.value_counts).plot.bar()

fig, ax = plt.subplots(figsize=(15,7))
df.groupby(['Month Number','Offense Category']).count()['Record Create Date'].unstack().plot(ax=ax);